### ISSUE TITLE
I have error when I try "npm start"

### ISSUE THREAD

**Issue by niypoo** [madhums/node-express-mongoose#21]
Hello Madhums ,
I Downloaded last version and install "npm install" - Work good - ,
but when I try " npm start " get error 
"
E:\NodeJS\node-Sherif>npm start
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\
npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! file E:\NodeJS\node-Sherif\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No value found for key start at 22:14
npm ERR!     "start": set "NODE_PATH=./config:./app/controllers NODE_ENV=development ./n
npm ERR!              ^
npm ERR! File: E:\NodeJS\node-Sherif\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
npm ERR! Please include the following file with any support request:
npm ERR!     E:\NodeJS\node-Sherif\npm-debug.log
"

and when try "node server.js" get error too "

module.js:338
    throw err;
    ^
Error: Cannot find module 'config'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\NodeJS\node-Sherif\server.js:16:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
"

What Can I do For throw this problem
"I Work on Windows 8.1"

**Comment by madhums** [comment]
Looks like its [related to NODE_PATH](https://github.com/madhums/node-express-mongoose-demo/search?q=node_path&type=Issues&utf8=%E2%9C%93). 

The error about not being able to parse package.json looks like an npm issue or something. Or if you have mistakenly renamed it to `package.js` ? There are couple of  [issues](https://www.google.nl/search?q=NODE_PATH+windows&oq=NODE_PATH+windows&aqs=chrome..69i57.3391j0j7&sourceid=chrome&es_sm=119&ie=UTF-8#q=node%20path%20windows%207)  you can find about node_path and windows
